# Generated by Django 4.0.1 on 2022-05-15 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
